#
###################################
# Site wide configuration
####################################
#
title: Gulliver's Development
email: taejukim.me@gmail.com
description: ..
url: https://gulliv.ml
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  avatar: logo.png
  name: gulliver's development
  job: "걸리버 개발기"
  email: "taejukim.me.gmail.com"
  disqus-shortname: "xownsla"
  facebook: "tj.kim.94402"
  github: "taejukim"
