# Setup
title:               blog.taeju.kim
tagline:             "TJ's blog"
description:         '<img src="/assets/images/photo.png">blog.taeju.kim'
url:                 https://blog.taeju.kim
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              taeju.kim
  url:               https://blog.taeju.kim
  email:             iam@taeju.kim

# Gems
plugins:
  - jekyll-paginate

# Build settings
markdown:       kramdown
highlighter:    rouge
include:
  - _pages

# Custom vars
version:             1.0.0
google_analytics_id: UA-158697523-1

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
