#
###################################
# Site wide configuration
####################################
#
title: Gulliver's Development
email: taejukim.me@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://gulliv.ml
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Gulliver
  job: "SW Engineer"
  bio: "Works in LGE"
  email: "taejukim.me.gmail.com"
  disqus-shortname: "xownsla"
  facebook: "xownsla"
  github: "taejukim"
