
# SEO settings
title: TAEJU.KIM
email: me@taeju.kim
description: ..
url: https://blog.taeju.kim
keywords: ["blog", "jekyll"]
google_analytics_id: UA-146764841-1
# baseurl: null

google_analytics: UA-146764841-1
repo: http://github.com/taejukim
disqus_shortname: "xownsla"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Taeju.Kim
  job      : SW Engineer
  # bio      : ""
  thumb    : /images/author.png
  email    : me@taeju.kim
  url      : http://blog.taeju.kim
  github   : http://github.com/taeju.kim
  facebook : http://facebook.com/taejukim.me

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
